### ISSUE TITLE
Add Deprecated warning to the readme

### ISSUE THREAD

**Issue by RomanGotsiy** [substack/https-browserify#7]
Hey,
AFAIK `browserify` doesn't use this lib anymore.
So Could you please add some "This lib is deprecated" warning to the README to not confuse other people.

For example, these guys (https://github.com/jspm/nodelibs-https) has copied this lib together with the issue #6

**Comment by feross** [comment]
This library *is* used by browserify.

https://github.com/substack/node-browserify/blob/8f5ebbf50544bdbdf34d4e0f336ac531152a5da4/package.json#L41
